export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
export const ADD_CHOP = 'ADD_CHOP';
export const ADD_RESULT = 'ADD_RESULT';
export const CHANGE_FUNCTION = 'CHANGE_FUNCTION';
export const CHANGE_PORK_TYPE = 'CHANGE_PORK_TYPE';
export const SET_LAST_RESP = 'SET_LAST_RESP';
